#include <gtkmm/window.h>
#include <gtkmm/scrolledwindow.h>
#include <gtkmm/grid.h>
#include <gtkmm/textview.h>
#include <gtkmm/label.h>
#include <gtkmm/main.h>
#include <glibmm/dispatcher.h>

Gtk::Grid *grid;
Gtk::Grid* addTextView(Glib::ustring text);

bool addViews() {
    grid->add(*addTextView("The only good thing that has come out of that final Hyouka episode is that it's made me want to start with this. Knowing KyoAni, they won't make any adaption of novel 5 for the foreseeable future."));
    grid->add(*addTextView("RTK a shit."));
    grid->add(*addTextView("What's the alternative, spending 11-12 years writing out Kanji again and again and learning barely 500 at the end of the entire thing? I'd rather go with RTK."));
    grid->add(*addTextView("Godspeed. Though you will need much more than just that."));
    grid->add(*addTextView(">>71710299\nYou won't make it. You won't enjoy it. Stop now. \n\nI started studying Japanese - as in, for a job there later, I do it with economics - 3 years ago, spent the last year in Japan and my hobby is Kanji to be frank, I learn them like mad. I also used RTK for the beginning, gets you going fast, after ~600 you just do it yourself. \n\nAnyway, I talk Japanese everyday. I read a whole lot of Manga raw. I watch my animu for Vocab. I even read one light novel - Suzumiya Haruhi, the 11th one. But. BUT.\n\nThat Light novel opened my Eyes. You do get your Furigana for almost everything in there, but written Novel Japanese is a whole other class then spoken. You'll see so many Kanji never used casually because \"hey, when we add readings, even our retard kids will know what that is\". Sadly, you gaijin won't. \n\nSo what will you get from reading Hyouka 5 by yourself, in Japanese? Let's say you study hard - let's say you even are motivated enough. I am 21, I don't know your age but learning languages will get harder when you are already old enough to 4chan. It'll take you at least 3 years, but I guess more, since frankly - I am a fucking genius nerd. Normal people will take 5 years to get on my level - 1300 Kanji, fluency in casual stuff. \n\nAnd that won't read you novels. Wait for Baka-Tsuki. Seriously."));
    grid->add(*addTextView(">>71710299\n>>this\ndumbass\nlearn kanji by radicals, you'll never learn them all using that shit."));
    grid->add(*addTextView("Don't learn japanese you need to be genius to know glorious nipponese."));
    grid->add(*addTextView(">>71714232\nWhat the fuck is this shit?\n\nIs this some type of joke?"));
    grid->add(*addTextView(">>71710557\nPay for someone to translate it for you?"));
    grid->add(*addTextView(">>71714232\n>but learning languages will get harder when you are already old enough to 4chan.\n\nIf you were a \"fucking genius nerd\" as you call it, you'd know that's a load of horseshit. It actually gets easier to learn new languages as you get older.\n\nWhy the fuck would you want to tell someone they can't do something they're working towards? You're welcome to be a pessimistic asshole, but don't let that shit spill out over into other people's lives. \n\nLet the guy try. It might be hard and he might give up after all, but at least he got to try it for himself."));
    grid->add(*addTextView(">>71710557\n>spending 11-12 years writing out Kanji again and again and learning barely 500 at the end of the entire thing?\nYou need to have some serious learning difficulties to achieve that feat."));
    grid->add(*addTextView(">>71714484\nI only said it to share some experience. \n\nThing is, I study with some 20 other dudes. The ones with the most problems are 31, 45 and 27 years old. The best 3 are me with 21, another 21 and a 24. \n\ngenius nerd is how I get treated, that was not to brag, really. I watch anime, that gets me fluent. So in class, I usually deliver good performance. I registered at the offices here without problems. Stuff you expect when learning a language. Still, they think of me as some kind of weird ass deity with no life.\n\nLearn for yourself and you may lose your motivation fast enough to forget what you learned already. I mean, where do you even start? Frankly, everywhere at the same time. All Hiragana at the beginning makes you reluctant to Kanji, Kanji alone makes you a retard who cannot into grammar for shit, Grammar without vocab is useless, and you still cannot speak - which you might as well, it's easy once you pay attention to animus.\n\nLearn with a class and the ones better then you might demotivate you. there's always that asian kid who knows his Kanji already. Or the genius nerd. \nClasses rarely live up to cost and expectations...\n\n\nThen again, I kinda agree. One should at least try for oneself. \nWas there anyone actually succeeding with /a/'s daily jap threads?"));
    grid->add(*addTextView("The only difficult you'll have is forgetting what you learnt for lack of practice. So keep forcing yourself to read stuff even if you can't make sense of everything."));
    grid->add(*addTextView(">>71715015\nMore than you think, although, the people who are really serious about it hang on in the IRC and talk with japanese people and stuff."));
    grid->add(*addTextView(">>71715145\nquite nice to hear. I like 4chan for collaborate efforts and original contents, after all. \n\nthis happens when you get hooked 2007, and are here forever.\n\nJapanese Translator here, ask me anything if you want."));
    grid->add(*addTextView(">>71710557\nI spent nearly 6 months learning all the useful Kanji on Kanjidamage, about 1700 of em, then I completed the rest through RTK and other sources, JPLT1 two years after I started studying japanese, you must be retarded to spend that much time"));
    grid->add(*addTextView(">>71715220\nHere's to hoping you remember something from when you started.\n\nI'm halfway through the second book covering grammar, Genki II, but I keep fucking up with words. What did you do to memorize that shit?"));
    grid->add(*addTextView(">>71714232\nIt does not take 5 years to learn 1300 kanji and basic fluency. You can learn the meaning and writing of thousands of kanji in a matter of months using RTK, and afterwards you can start picking up readings one at a time through novels and manga over the course of a year (the most common and useful readings will naturally tend to be learned first since they are the> >most common and useful readings<<)\n\nI'm not saying it doesn't take work but if you are reading and looking up words every day it is not impossible by any means, and there is certainly no need for anyone to just give up."));
    grid->add(*addTextView(">>71710299\nIt's good on it's own, but it still will only get you part way there. Focus on making your own meanings and stories, some of the ones in the book are fucking useless."));
    grid->add(*addTextView(">>71715504\n>>71715399\nThese.\n\nAlso, why do people keep on sucking RTK dick when glorious KANJIDAMAGE exists?"));
    grid->add(*addTextView(">>71715220\nDo you work commercially? Whats the best way to start out if you're currently doing English teaching in Japan?"));
    grid->add(*addTextView(">>71715220\nHow does one go about becoming a translator? I mean, obviously you have to be fluent to some degree and be able to write really well in English, but are there courses? Do you take special training? Is it like fine arts and writing where you need to have a portfolio built up of shit you've already done?\n\nSorry for the barrage of questions, I'm just really interested in doing this as a career. Respectable translator of high literature by day, scanlating doujins and VNs by night. Lets me keep up a decent normalfag front while still getting to indulge in my hobbies."));
    grid->add(*addTextView(">>71715618\nKanjidamage is fine too. I like to have a physical object I can carry around so I recommend RTK personally. Also I can't remember but does Kanjidamage show stroke order? I dont' think it's super important after a point (I follow it mostly but there are a few radicals I take shortcuts on), but it is kind of useful to know how to count strokes correctly."));
    grid->add(*addTextView(">>71715780\nHa, the shit I see on T.V. here everyday makes me think the exact opposite of what you're saying. English > Dutch translation is so bad sometimes you'd think they hired monkeys.\n\nMaybe it's different in books, though, I don't know. I always try to get books in English."));
    grid->add(*addTextView(">>71715618\nBecause with KanjiDamage its either that fag's story or your own. On koohii you can pick from dozens of alternative stories Plus who wants to incorporate the readings into the story? That makes em even harder to remember. \nI do use kanjidamage to look at the most common jukugo though, and sometimes heisigs keywords are shit, so I just compare them the kanjidamage's keyword and maybe use that."));
    grid->add(*addTextView(">>71715441\nOh boy, fucking words. I still confuse some of those. Especially those who don't have Kanji for them, for some reason having those really helps me remember shit. \n\nHow does one do it? \n\nEasy cases (with Kanji): Learn everything there is about that word - examine the Kanjis it's made up of, try to get the intonation down. \n\nHard cases: List them up, spent a WHOLE DAY having that one word floating in your head and make a sentence with it every hour. \n\nI'm dead fucking serious. I used that to remember bullshit like ぼろぼろ、　ぼこぼこ、ぱりぱり、つやつや or those like ぴったり、あっさり、ぎっちり　etc.\n\n>>71715690\nnah, only for 4chan here and there. I still study.\n\n>>71715780\nI wouldn't. Translators loose jobs all around the globe every day thanks to companies saying \"just get us a random native who can make sense out of google translate\". \nIt usually goes like this, you learn the language and have to be able to read a sentence, and give it back in your language, all implications and references included. There's schools for it I hear, knowing your own language VERY good helps a lot. Fluency is the ticket to the fast lane, but looking up a word or a construction doesn't hurt. \n\nReferences of your work will help when applying at a company, but many translators freelance. I know i wouldn't, but then there's also the danger of getting laid off. Econimically, try to get some other specialized knowledge into you as well."));
    grid->add(*addTextView(">>71715911\nWell, that's half the reason I want to get into translating; seeing fairly high-profile foreign movies coming over with garbage subtitles when they clearly have to know better is actually painful to me.\n\nA good or bad translation can make or break a particular work regardless of how good the source material is; I just want to bring over stuff people would never see otherwise, as best as it can possibly be. It's really sad to see when people simply do not give a fuck and run it all through Google Translate to save a few bucks."));
    grid->add(*addTextView("KyoAni had a thing or two for improving the source novels. That means Hyouka actually sucks, and you're gonna regret learning all these just for that."));
    grid->add(*addTextView(">>71716004\nThere exist people who can make sense out of Google Translate? I never knew."));
    grid->add(*addTextView(">>71716004\n>\"just get us a random native who can make sense out of google translate\"\n\nThat's what it seems like half the time. The only real posts seem to be for big businesses, law, or the really specialized tech/IT stuff, so you need to be competent in that field on top of everything, and know all the specialized vocab for it.\n\nFuck it, I'll do what I like anyway and be good enough at it that people will have to recognize it. There's always people out there willing to pay extra for quality, right?\n\n...right? ;_;"));
    grid->add(*addTextView(">>71715504\nThis is what I'm doing but without writing. \nI'm having trouble with the vocab but I'm getting to it slowly."));
    grid->add(*addTextView(">>71716135\nI don't know if they really exist, but there's guys getting paid for doing this.\n\nNeedless to say, this is how instuction manuals are made."));
    grid->add(*addTextView("I'm just sharing this for people who might profit from it. I certainly helps me a great deal.\n\nhttp://lazunin.com/kage_en.html"));
    grid->add(*addTextView(">>71716232\nSpecializing yourself is not that hard, and may even come with your job. Heck, you can even translate games, just specialize in Localization. Which comes with the cool side effect of getting to play games in debug."));
    grid->add(*addTextView(">>71716232\n>There's always people out there willing to pay extra for quality, right?\n\nYeah, this is the problem. The bean-counters don't care about quality. Subs in particular seem to be the absolute last thing on people's minds.\n\nThe other way to go is to get an academic post in Japanese (e.g. Rubin). Then you can do whatever the hell you want. But of course that's even harder."));
    grid->add(*addTextView(">>71716645\nThat's...disappointing, probably because deep down I know it's true but just don't want to admit it.\n\nWell, fuck it. Won't know for sure until I try, and what I do know is I really enjoy what little translating I've done.\n\nThanks for the advice."));
    grid->add(*addTextView(">>71715220\nDid you go to class or self-taught?"));
    grid->add(*addTextView("I'm up to 1500 kanji on RTK myself, I should have the first book and the 200 new joyo kanji down in about a month.\n\nI see quite a lot of dislike for RTK on these boards for some reason, is it because it doesn't teach you the on readings or something? You can learn those later. RTK teaches you how to write each kanji and differentiates them from other kanji using a meaning. It's the same advantage the chinese have in learning japanese. They don't need to \"learn\" the kanji because they already know them, they just attach new meanings and usage to them."));
    grid->add(*addTextView("For those wondering if you can be a translator, try this:\nhttp://gengo.com/translator-team/become-a-translator/\n\nI tried. Turns out I don't even know English (which isn't my first language) good enough. ;_;"));
    grid->add(*addTextView(">>71716949\nWow, what a fucking moron you are.\n\nFirstly, Chinese people learn simplified character forms, and use each one differently. A Chinese speaker will have NO IDEA how to read shit in Japanese not only because they don't use traditional, but because they aren't even REMOTELY similar in the way they are used.\n\n>You can learn those later\nOhoho. You don't 'have the kanji dow'n because you only very vaguely know what they mean and have no fucking idea how to pronounce them. They are effectively meaningless; you can't understand shit from its kanji alone. You're going to struggle for the next five years mapping random sounds to random squiggles. Have fun with that."));
    grid->add(*addTextView(">>71717063\n>Turns out I don't even know English good enough.\n>Turns out I don't even know English well enough.\n\nGengo pays about 2 cents per kana/kanji. I wonder what that comes out to for a typical job."));
    grid->add(*addTextView(">>71717168\n>Ohoho. You don't 'have the kanji dow'n because you only very vaguely know what they mean and have no fucking idea how to pronounce them. They are effectively meaningless; you can't understand shit from its kanji alone. You're going to struggle for the next five years mapping random sounds to random squiggles. Have fun with that.\n\nOnly no. RTK works wonders for starting Japanese, and later you can learn the reading by themselves if you want so much. \nI'm not going to argue anymore in favor of it because I don't honestly care that much but different ways work for different people. \n\nAlso, stop calling names on the internet."));
    grid->add(*addTextView(">>71717168\n>Random squiggles\nThey won't be randoms squiggles because you'll be familiar with many of the kanji.\n>Random sounds\nAre you somehow able to voice kanji from their visuals? Do the strokes give a clue to the pronunciation? No. Not even the japanese learn kanji that way. You're arguing that RTK will hurt you, yet you probably spent time learning individual kanji at the same time you were associating it with these random sounds."));
    grid->add(*addTextView(">>71717286\n>RTK works wonders for starting Japanese\nI completely agree. It taught me plenty about stroke ordering and helped me get a few kanji under my belt.\n\nI dropped it almost immediately after as I began to realise that, ultimately, it seemed very promising but WOULD leave you high and dry. You can't just separate pronunciation from the characters, otherwise they're just arbitrary bunches of lines. It's not a question of learning the readings 'if you want so much' - it's a case of 'if you don't, then you're wasting your time, and what are you even doing learning Japanese?'\n\nAlso, it's tough love. He'll thank me when he drops that cancerous RTK."));
    grid->add(*addTextView(">>71717168\nThere's a different between knowing the character and its strokes and knowing their readings.\n\nRTK is a helpful tool to learn the first part, and all I see is you bitching about how it doesn't teach you the second as well?\n\nI also never said the chinese knew the reading from the start, they know the characters and how to write them, and that's what's important."));
    grid->add(*addTextView(">>71717266\nI wish grammar nazi weren't extinct. Then my English would actually improve from browsing 4chan."));
    grid->add(*addTextView(">>71717432\nRTK is there to ease you into Kanji, not teach you them. But learning the Onyumi of every Kanji is pointless with all the exceptions. Learn words instead. \nAfter learning words you get to read, and you learn the reading on the way.\n\nIt's not tough love, you're just being a dick on the internet thinking your method is the best while it's clear that there's no right way in approaching the language."));
    grid->add(*addTextView(">>71717168\n>Firstly, Chinese people learn simplified character forms, and use each one differently. A Chinese speaker will have NO IDEA how to read shit in Japanese not only because they don't use traditional, but because they aren't even REMOTELY similar in the way they are used.\n\nThis is completely wrong. If the person is well read enough, he'll be able to recognize most traditional characters just fine. Even if he had no idea what a character was, he could very well use context clues to figure it out. (There's also the fact that Japanese kanji can sometimes resemble simplified Chinese more than traditional Chinese, but that's another matter.)\n\nIn regards to Japanese, there are many words that have etymological roots in Chinese and have retained the same basic meaning. Even without any knowledge of grammar, depending on how many of these Chinese origin words are used in the sentence, the Chinese reader could get a pretty good idea at what the sentence is saying."));
    grid->add(*addTextView("For kanji, I just use JLPT decks on Anki, read every day, and add new words/phrases to Anki decks. Seems to be working so far."));
    grid->add(*addTextView(">>71717432\nI agree with you on this point. If you don't keep your vocab and grammar learning to max after RTK, those 2 thousand kanji will begin to seem more and more abstract. You have to keep putting them to use. This is incredibly hard because of the high number of kanji. Anyway, I'm still gonna complete RTK because it'll only take a couple more weeks, and I'll at least be able to put to use the common kanji (some of which are near the end)."));
    grid->add(*addTextView(">learning a new language just because of some chinese cartoons\n\n>>>/jp/"));
    grid->add(*addTextView(">>71717676\n>Being a faggot just because of some dicks \n\n>>>/cm/"));
    grid->add(*addTextView("You can easily learn 200 words daily (with kanji) if you are a NEET and have the patience.\n\nIt takes me about 6 hours to learn 200 words (with kanji) while reviewing 100-200 but I learn (much) faster than most people so most people could probably reasonably aim for 100 in 6 hours. 6 hours a day if you're a NEET leaves you with another ~8 to enjoy yourself so you don't have to just give up what makes you happy.\n\nIt would probably be much harder for non-NEETs though. \n\nJust make sure you review EVERY DAY.\n\nReview at least 100-200 words every day on top of studying new ones."));
    grid->add(*addTextView(">>71717676\nenjoy your hadena subs"));
    grid->add(*addTextView(">>71717394\n>Are you somehow able to voice kanji from their visuals\nYes. Going back to what the OP said about Chinese, this is even MORE the case.\n我们 = wo3men = We\n我 + 门 = I + door radical = wo3 + men\n>Do the strokes give a clue to the pronunciation?\nYes, they should be evocative of that. That's the point. You say a sound and it evokes the character. If you just know the character you've got nothing to evoke and you can't understand or say shit.\n>No. Not even the japanese learn kanji that way.\nThe Japanese learn kanji as integrated into language learning itself, not in some bloody vacuum independent from the language entirely.\n\n>>71717513\n>Learn words instead.\nI agree.\n> there's no right way in approaching the language.\nYeah, maybe if you look hard enough at the wall you'll learn Japanese too. I'm a dick to tell someone that there are much BETTER ways of learning, right?\n\n>>71717539\n>This is completely wrong. If the person is well read enough, he'll be able to recognize most traditional characters just fine.\nReally, really not true, sorry. Even if you go to most Chinese webpages, they offer the ENTIRE site translated as another language for traditional-writers.\n\n>>71717606\nIf you're far into it, as in, more than halfway, then you may as well finish, but don't expect that you'll retain that knowledge unless you drill constantly is all I'm saying."));
    grid->add(*addTextView(">>71717784\n>Yeah, maybe if you look hard enough at the wall you'll learn Japanese too. I'm a dick to tell someone that there are much BETTER ways of learning, right?\nBetter for you. Not better for everyone. \nStop acting as if you're saving him from some terrible fate by imposing your opinion on him."));
    grid->add(*addTextView(">>71716937\nBoth, I study that shit. I'm a fan-translator, so i'm not really best of the best. But I do it.\n\n>>71717394\nBut they sometimes do. \nFor instance, when your Kanji has 士 'shi' to it, it will most probably have at least one on-yomi 'shi'. \n\n志　誌　仕　至(ok, bit of a strech here because it's actually 土 not　士)\n\nMany others work that way, radicals, bitch."));
    grid->add(*addTextView(">>71717266\nthink ~1000 Kana/Kanji for one A4 Page."));
    grid->add(*addTextView("How did it make you do that? I haven't seen it."));
    grid->add(*addTextView(">>71717735\nI'm a neet, but I don't have enough patience for a daily many hour Anki masturbation. Also I don't like the idea of learning words outside of context.\nInstead, I'm just reading Japanese blogs, 2ch, pixiv comics, etc with rikaisama everyday when I feel like it. I guess it can hardly be called studying, but I still learn quite a few words and kanji that way, while fully enjoying myself doing it."));
    grid->add(*addTextView(">>71716135\nThere are quite a few i know of who use it to translate chinese novels. they're pretty good at it, the quality of translation is even better than some of the translations at baka-tsuki."));
    grid->add(*addTextView("Sorry OP, you're going to fail, just like everyone before you.\n\nWe have this thread on /a/ every week, and every second day on /jp/. It's always about someone who just started, or about someone who wants to brag how he knows 200 kanji. Then they give up, and we never see them again.\n\nOpening a thread is a red flag for eventual failure. The VNfags who acually learned Japanese talk about VNs, and never about learning."));
    grid->add(*addTextView(">>71718345\n>>>/jp/"));
    grid->add(*addTextView(">>71718345\nYeah, it's funny how people talk so much about the ways they should learn it \"the right way\", instead of actually fucking learning it whatever way."));
    grid->add(*addTextView(">>71718262\nyou DO know that you can use context in anki right?"));
    grid->add(*addTextView(">>71718345\nWhy would they ever post about it again? It's not like anyone is going to remember them."));
    grid->add(*addTextView(">>71718470\nIt's better if the context is familiar to you, like a line from a VN or something, than just some random sentence.\nSure, you can also add your custom sentences to anki, but it's too much work for me."));
    grid->add(*addTextView(">>71718604\nThen, in order: kana>grammar>kanji(learning as you read)?"));
    grid->add(*addTextView(">>71716295\nLooks interesting, I'll give it a try. Do you happen to know if there's a Kanji Damage kanji file around anywhere?"));
    grid->add(*addTextView(">>71718604\nah, then you probably won't get very far, not if you don't put in even a bit of effort. the way i do it is I keep a list of stuff i'm interested in that i read frequently, and i also prune regularly, stuff that look important/interesting i then transfer to anki. minimum effort really."));
    grid->add(*addTextView(">>71719566\nAs I said, I'm just reading stuff I want to read, which is mostly blogs and 2ch threads. If I'm really interested I can even read LNs, though it takes much more effort, of course. I have read a couple of chapters of Hyouka with yomichan before getting bored and skipping to interesting parts, for example."));
    grid->add(*addTextView(">>71714232\n> I am a fucking genius nerd. Normal people will take 5 years to get on my level - 1300 Kanji, fluency in casual stuff.\n\nLOL It took me 6 months and I'm not even a genius, let alone be a nerd."));
    grid->add(*addTextView(">>71720609\n> posting on /a/\n> not a nerd\nseriously..."));
    grid->add(*addTextView(">>71720765\nI post on /fit/, /lit/, /ck/, /sci/, /k/, /g/, /sp/, /tg/ and /v/. I believe having diversified hobbies doesn't make one nerd, just someone who want to enjoy everything he likes."));
    grid->add(*addTextView("Since we have this thread, might as well ask.\n\nFuck, I have just started studying japanese, been using a sort of online textbook (textfugu) which more or less guides me nicely over grammar, up to this point had no problem over that front. I already feel confident enough with Kata/Hiragana\n\nHowever, vocab and specially kanji are a pain in the ass. After this month, my kanji anki deck rght now has around 43 kanji. After a fucking month. And I have a lot of problem with readings (meanings and kanji vocab are a-ok, tho). \n\nThis is gonna take forever to finish at this pace, and I can't increase my speed because that will just fuck over my readings. \n\nVocab list are also a pain. I take 2-3 days to get somewhat confortable with a 50 word list, all hiragana, for example, and forget a lot of them after a while.\n\n\nTL;DR: How can I get this stuff in my brain? I can't into mnemonics, for some reason."));
    grid->add(*addTextView(">>71721144\nKanjidamage and random vocab on Anki helped me learn 120 of both in 6 days."));
    grid->add(*addTextView(">>71721220\n>random vocab on Anki\n\nGot the link to a good Japanese vocab deck on Anki?"));
    grid->add(*addTextView(">>71721144\n>After this month, my kanji anki deck rght now has around 43 kanji. After a fucking month.\nNo no no, you should use a premade list for kanji most of the time. There are many RTK decks and a good Kanji Damage deck already out there, just download one and do however many kanji a day. Also get a premade vocab deck to use, but make your own deck as well (basically like you've been doing) with words you haven't learned yet and kanji you think you'll be seeing a lot before your kanji deck shows them."));
    grid->add(*addTextView(">>71721252\nI use coreplus one, vocab only. I can't say if it's good. But since I'm learning kanji and grammar before I can read mango and LN, it can't hurt to learn vocab together."));

    grid->show_all();
    return false;
}

Gtk::Grid* addTextView(Glib::ustring text) {
	Gtk::Grid *ngrid = new Gtk::Grid();
	Gtk::TextView *tv = new Gtk::TextView();
	Glib::RefPtr<Gtk::TextBuffer> tb = tv->get_buffer();
	tv->set_wrap_mode(Gtk::WRAP_WORD);
	tv->set_editable(false);
	tv->set_cursor_visible(false);
	tv->set_hexpand(true);

	tb->insert(tb->begin(), text);
	Gtk::Label *label = new Gtk::Label("--------------");
	ngrid->attach(*label, 0, 0, 1, 1);
	ngrid->attach(*tv, 0, 1, 1, 1);

	return ngrid;
}



int main() {
	Gtk::Main kit(0, NULL);

	Gtk::Window *win = new Gtk::Window(Gtk::WINDOW_TOPLEVEL);
	win->set_default_size(500, 800);


	Gtk::ScrolledWindow *sw = new Gtk::ScrolledWindow();
	grid = new Gtk::Grid();
	sw->set_policy(Gtk::POLICY_NEVER, Gtk::POLICY_AUTOMATIC);
	grid->set_orientation(Gtk::ORIENTATION_VERTICAL);
	sw->add(*grid);
	win->add(*sw);

	win->show_all();
	//Glib::signal_timeout().connect_seconds(sigc::ptr_fun(&addViews), 3);
	addViews();

	kit.run(*win);
	return 0;
}

